// Generated by scripts/generate-content-dates.mjs. Do not edit manually.
export const contentDates: Readonly<Record<string, string>> = {
  "/incorporation-101": "2026-06-23",
  "/interview-guidebook": "2026-07-20",
  "/programs": "2026-08-17",
  "/programs/launch-station": "2026-07-29",
  "/resources": "2026-09-03",
  "/resources/application-guide": "2026-07-15",
  "/resources/choosing-the-right-co-founder": "2026-07-20",
  "/resources/dos-and-donts": "2026-07-20",
  "/resources/ecosystem-database": "2026-09-05",
  "/resources/encouraging-leadership": "2026-06-23",
  "/resources/engagement-during-fundraising": "2026-06-23",
  "/resources/finding-a-co-founder": "2026-07-20",
  "/resources/founders-frequently-asked-questions": "2026-06-23",
  "/resources/leadership-in-funding-rounds": "2026-06-23",
  "/resources/lessons-learned": "2026-07-20",
  "/resources/negotiating-with-lead-investors": "2026-06-23",
  "/resources/the-role-of-expertise": "2026-06-23",
  "/resources/warm-introductions": "2026-07-20",
  "/resources/y-combinator-101": "2026-06-23"
};
