// Generated by scripts/generate-content-dates.mjs. Do not edit manually.
export const contentDates: Readonly<Record<string, string>> = {
  "/ikigai-launchpad": "2026-10-01",
  "/incorporation-101": "2026-09-30",
  "/interview-guidebook": "2026-09-30",
  "/launch-station": "2026-10-01",
  "/resources": "2026-09-30",
  "/resources/application-guide": "2026-09-30",
  "/resources/choosing-the-right-co-founder": "2026-09-30",
  "/resources/dos-and-donts": "2026-09-30",
  "/resources/ecosystem-database": "2026-09-30",
  "/resources/encouraging-leadership": "2026-09-30",
  "/resources/engagement-during-fundraising": "2026-09-30",
  "/resources/finding-a-co-founder": "2026-09-30",
  "/resources/founders-frequently-asked-questions": "2026-09-30",
  "/resources/leadership-in-funding-rounds": "2026-09-30",
  "/resources/lessons-learned": "2026-09-30",
  "/resources/negotiating-with-lead-investors": "2026-09-30",
  "/resources/the-role-of-expertise": "2026-09-30",
  "/resources/warm-introductions": "2026-09-30",
  "/resources/y-combinator-101": "2026-09-30"
};
